"""Turn a drawing sheet into images a vision model can actually read.

Drawings are not pages. The corpus's electrical sheets are A1 and A0 --
2384 x 1684 and 3370 x 2384 points -- and the annotation on them is
drawn at 6 to 10 point, with the tenth percentile down at 3. Rendered
whole and handed to a model, an A0 sheet arrives downscaled to a
thumbnail in which "1500kVA" and "150 kVA" are the same smear. That is
the failure this module exists to prevent, and it is the worst one
available: a confident wrong figure is more damaging than no figure.

So: render at a DPI derived from the sheet's own smallest text, then cut
the bitmap into overlapping tiles, and send the tiles. One reduced
overview goes with them so the model can say where on the sheet a tile
sits and can read the title block, which is the provenance.

`pypdfium2` is the renderer because dcp/extract.py already uses it for
the OCR fallback; adding a second rasteriser would give the project two
answers to what a page looks like.
"""

from __future__ import annotations

import base64
import io
import math
from dataclasses import dataclass
from pathlib import Path

# The rendered height, in pixels, that the smallest text on the sheet
# should reach. Measured against the corpus rather than assumed: at 9 px
# a 3 pt annotation on Dundee's transformer sheet resolves "1500kVA" and
# "33000 / 400V"; at 6 px it does not.
TARGET_MIN_TEXT_PX = 11.0

# Bounds on the derived DPI. The floor is what an A4 specification sheet
# needs and no more; the ceiling stops a sheet carrying one degenerate
# zero-height character from demanding a 100-megapixel render.
MIN_DPI = 150.0
MAX_DPI = 320.0

# Tile geometry, in rendered pixels. 1600 is chosen against the model's
# own image handling rather than aesthetics: a tile appreciably larger
# gets downscaled again on the way in, which undoes the DPI.
TILE_PX = 1600
TILE_OVERLAP = 0.12

# Above this a sheet costs more than it can be worth in a pilot, so the
# DPI is walked back until it fits rather than the sheet being dropped.
MAX_TILES = 12

# The whole sheet, small, for context and the title block.
OVERVIEW_LONG_EDGE = 1400


@dataclass(frozen=True)
class Tile:
    """One rendered piece of a sheet, and where on the sheet it came from."""
    index: int
    row: int
    col: int
    rows: int
    cols: int
    png: bytes
    # Fractions of sheet width/height, so the review sheet can say
    # "upper-left quarter" without knowing the render DPI.
    left: float
    top: float
    right: float
    bottom: float

    @property
    def quadrant(self) -> str:
        """Plain-English position, for the hand-check sheet.

        From the tile's centre, not its top-left corner: tiles overlap
        by design, so on a 3x4 grid the first two columns both start in
        the left third and naming them from their corners called both
        of them "left".
        """
        vert = ("top", "middle", "bottom")[
            min(2, int((self.top + self.bottom) / 2 * 3))]
        horiz = ("left", "centre", "right")[
            min(2, int((self.left + self.right) / 2 * 3))]
        return f"{vert}-{horiz}"

    @property
    def position(self) -> str:
        """Unambiguous grid position, which the model is told to quote."""
        return (f"tile {self.index} (row {self.row} of {self.rows}, "
                f"column {self.col} of {self.cols}, {self.quadrant})")

    def data_url(self) -> str:
        return "data:image/png;base64," + base64.b64encode(self.png).decode()


@dataclass(frozen=True)
class RenderedSheet:
    page_index: int
    width_pt: float
    height_pt: float
    dpi: float
    overview: bytes
    tiles: tuple[Tile, ...]

    @property
    def overview_data_url(self) -> str:
        return "data:image/png;base64," + base64.b64encode(self.overview).decode()


def smallest_text_pt(pdf_path: Path, page_index: int) -> float | None:
    """The 10th-percentile character height on a page, in points.

    The percentile and not the minimum: PDFs generated by CAD exporters
    routinely carry a handful of zero- and sub-point characters that are
    clipping artefacts, and sizing the render to those would push every
    sheet to the DPI ceiling for nothing.
    """
    try:
        import pdfplumber
    except ImportError:
        return None
    try:
        with pdfplumber.open(str(pdf_path)) as pdf:
            if page_index >= len(pdf.pages):
                return None
            sizes = sorted(c["size"] for c in pdf.pages[page_index].chars
                           if c["size"] and c["size"] > 0.5)
    except Exception:
        return None
    if not sizes:
        return None
    return sizes[max(0, int(len(sizes) * 0.10) - 1)]


def choose_dpi(pdf_path: Path, page_index: int) -> float:
    small = smallest_text_pt(pdf_path, page_index)
    if small is None:
        # No text layer at all: the sheet is a scan or pure vector, and
        # nothing measurable says how small its lettering is. The
        # ceiling is the safe guess -- these are the sheets where a
        # misread is likeliest.
        return MAX_DPI
    dpi = TARGET_MIN_TEXT_PX / (small / 72.0)
    return max(MIN_DPI, min(MAX_DPI, dpi))


def _tile_grid(width_px: int, height_px: int) -> tuple[int, int]:
    step = TILE_PX * (1 - TILE_OVERLAP)
    cols = max(1, math.ceil((width_px - TILE_PX * TILE_OVERLAP) / step))
    rows = max(1, math.ceil((height_px - TILE_PX * TILE_OVERLAP) / step))
    return rows, cols


def render_sheet(pdf_path: Path, page_index: int = 0) -> RenderedSheet:
    """Render one page to an overview plus overlapping tiles."""
    import pypdfium2 as pdfium
    from PIL import Image

    pdf = pdfium.PdfDocument(str(pdf_path))
    try:
        page = pdf[page_index]
        w_pt, h_pt = page.get_size()
        dpi = choose_dpi(pdf_path, page_index)

        # Walk the DPI down until the sheet fits the tile budget. Losing
        # resolution is a real cost, so it is spent only when a sheet
        # would otherwise cost twelve times the pilot's per-document
        # budget, and the DPI actually used is recorded on the result.
        while True:
            scale = dpi / 72.0
            w_px, h_px = int(w_pt * scale), int(h_pt * scale)
            rows, cols = _tile_grid(w_px, h_px)
            if rows * cols <= MAX_TILES or dpi <= MIN_DPI:
                break
            dpi = max(MIN_DPI, dpi * 0.85)

        bitmap = page.render(scale=dpi / 72.0)
        full = bitmap.to_pil().convert("RGB")
        w_px, h_px = full.size
        rows, cols = _tile_grid(w_px, h_px)

        buf = io.BytesIO()
        ov = full.copy()
        ov.thumbnail((OVERVIEW_LONG_EDGE, OVERVIEW_LONG_EDGE), Image.LANCZOS)
        ov.save(buf, format="PNG", optimize=True)
        overview = buf.getvalue()

        step_x = (w_px - TILE_PX) / (cols - 1) if cols > 1 else 0
        step_y = (h_px - TILE_PX) / (rows - 1) if rows > 1 else 0
        tiles: list[Tile] = []
        for r in range(rows):
            for c in range(cols):
                left = int(c * step_x)
                top = int(r * step_y)
                right = min(w_px, left + TILE_PX)
                bottom = min(h_px, top + TILE_PX)
                crop = full.crop((left, top, right, bottom))
                b = io.BytesIO()
                crop.save(b, format="PNG", optimize=True)
                tiles.append(Tile(
                    index=len(tiles) + 1, row=r + 1, col=c + 1,
                    rows=rows, cols=cols, png=b.getvalue(),
                    left=left / w_px, top=top / h_px,
                    right=right / w_px, bottom=bottom / h_px))
        return RenderedSheet(page_index, w_pt, h_pt, dpi, overview, tuple(tiles))
    finally:
        pdf.close()


def sheet_pages(pdf_path: Path) -> int:
    import pypdfium2 as pdfium
    pdf = pdfium.PdfDocument(str(pdf_path))
    try:
        return len(pdf)
    finally:
        pdf.close()
