#!/usr/bin/env python3
"""Write the committed ownership record from the raw Companies House pull.

`data/external_sources/companies-house-ownership.yaml` is **generated** —
do not hand-edit it. It exists because `data/raw/` is not committed, and
a clone with no raw snapshots in it still has to be able to show who
lends to and who owns each scheme vehicle, with dates.

What it carries per company, and why each part is here rather than a
by-product of the capacity hunt:

  * **charges** — the lender, the date the security was created and
    whether it is still outstanding. On a single-asset SPV the lender is
    routinely the only party named above it in any public record, and a
    refinancing is dated to the day.
  * **psc** — the people and entities with significant control, *and*
    the statements. A statement of "no registrable person" is the
    disclosure a US- or Jersey-parented scheme actually makes: an
    overseas LP is not a registrable relevant legal entity, so the chain
    above it never reaches this register. Recorded as a statement with
    its own wording, never as an empty list.
  * **beneficial owners**, for companies on the Register of Overseas
    Entities. That register asks a question the PSC register does not,
    and for the Vantage vehicles it is answered — which is why a Jersey
    company can be a *better* ownership source than a UK one.
  * **officers**, corporate ones especially: a corporate director or
    secretary registered at the same address as a group's other
    vehicles is often what connects them.
  * **accounts filed** — every accounts filing with the date it was made
    up to, so a figure read from one can be dated to its year rather
    than to "the latest", and so a company that has filed **none** is
    recorded as having disclosed nothing rather than as a gap.

Usage:
    scripts/ch_write_ownership.py --filings data/raw/companies_house/filings_YYYY-MM-DD.json
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

import yaml

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from dcp import companies_house as ch

OUT = ch.EXTERNAL / "companies-house-ownership.yaml"

HEADER = """\
# Who lends to and who owns each scheme vehicle, from Companies House.
#
# GENERATED by scripts/ch_write_ownership.py from a raw pull under
# data/raw/companies_house/ — do not hand-edit. The hand-adjudicated
# half, which company is which scheme, lives in companies-house-spvs.yaml
# beside this file.
#
# Why four registers and not one. The PSC register is structurally
# unable to describe an overseas-parented scheme: an overseas limited
# partnership is not a registrable relevant legal entity, so the page
# reads "no-individual-or-entity-with-signficant-control" — Companies
# House's own misspelling — and the chain above it is never recorded.
# UK Court Lane DC Ltd reads exactly that way, and the two things that
# do say something about its ownership are the charges register (NFO
# Holdings, LLC, then Trimont Europe Limited) and the accounts'
# parent-undertaking note. So charges, PSC, beneficial owners and
# officers are all recorded, and none is treated as sufficient alone.
#
# A company on the Register of Overseas Entities is the mirror image:
# it files no accounts at all, so it discloses no capacity and no
# solvency position — but it must name its beneficial owners, which a
# UK company with an overseas parent need not. Every Vantage vehicle
# here is a Jersey company that names DigitalBridge Group, Inc.
#
# `charges_probed: true` means the charges endpoint was asked and
# answered. The profile's `has_charges` flag is not used to decide
# whether to ask: it read false for 44 of the 49 companies here that
# do carry charges, so gating the request on it would have recorded 44
# measured negatives that were never measured.
#
# `shareholders` comes from the confirmation statement, which answers a
# narrower question than the PSC register — who holds the shares, rather
# than who has significant control — and answers it for companies where
# the PSC register is silent. UK Court Lane DC Ltd's PSC page reads "no
# registrable person"; its CS01 says all seven ordinary shares are held
# by UK COURT LANE DC HOLDINGS, LP.
#
# Two things about that field. It is **extracted, not OCR'd**:
# confirmation statements are filed electronically and carry a text
# layer, unlike the scanned accounts, so no figure here rests on a
# character recognition. And `confirmation_statement.date` is the date of
# the filing the names were read from, which is often not the most recent
# one — a "confirmation-statement-with-no-updates" carries no shareholder
# block by definition, so the history is walked back to the most recent
# filing that names holders. A shareholder list stays true until it is
# superseded; the date says as of when.
#
# An empty `shareholders` is not always a failure to read. **Overseas
# entities and LLPs do not file a CS01 at all** — 21 of the companies
# here are one or the other, and for them the field is empty because the
# form does not exist, not because the filing was unreadable. Their
# equivalent disclosure is the beneficial-owner statement in `psc`, which
# for an overseas entity is compulsory and is often more informative than
# a UK company's PSC page.
"""


def entry(c: dict, shareholders: dict | None = None) -> dict:
    psc = c.get("psc") or {}
    persons, statements = [], []
    for p in psc.get("persons", []):
        ident = p.get("identification") or {}
        persons.append({
            "name": p.get("name"),
            "kind": p.get("kind"),
            "notified_on": p.get("notified_on"),
            "ceased_on": p.get("ceased_on"),
            "nationality": p.get("nationality"),
            "registered_in": (ident.get("country_registered")
                              or ident.get("place_registered")),
            "registration_number": ident.get("registration_number"),
            "natures_of_control": p.get("natures_of_control"),
        })
    for s in psc.get("statements", []):
        statements.append({"statement": s.get("statement"),
                           "notified_on": s.get("notified_on"),
                           "ceased_on": s.get("ceased_on")})

    charges = [{
        "created_on": ch_["created_on"],
        "status": ch_["status"],
        "satisfied_on": ch_["satisfied_on"],
        "persons_entitled": [p for p in ch_["persons_entitled"] if p],
    } for ch_ in c.get("charges", [])]

    corporate_officers = [{
        "name": o["name"], "role": o["role"],
        "appointed_on": o["appointed_on"], "resigned_on": o["resigned_on"],
        "registration_number": (o.get("identification") or {}).get(
            "registration_number"),
    } for o in c.get("officers", [])
        if (o.get("role") or "").startswith("corporate")]

    accts = [{"made_up_to": a["made_up_to"], "filed": a["filed"],
              "description": a["description"]}
             for a in c.get("accounts_filings", [])]

    out = {
        "company_number": c["company_number"],
        "company_name": c["company_name"],
        "status": c["status"],
        "type": c["type"],
        "incorporated": c["incorporated"],
        "registered_office": ", ".join(
            v for k, v in (c.get("registered_office") or {}).items()
            if k != "country" and v),
        "accounts_category": ((c.get("accounts") or {}).get("last_accounts")
                              or {}).get("type"),
        "accounts_filed": accts,
        # A company that has filed no accounts discloses nothing. Said
        # here in one field so it reads as a measured null.
        "discloses_nothing_no_accounts_filed": not accts,
        "charges_probed": True,
        "charges": charges,
        "psc": {"persons": persons, "statements": statements},
        # Who holds the shares, which is a narrower question than who has
        # significant control and is answered for companies where the PSC
        # register is silent. Extracted from the confirmation statement's
        # text layer rather than OCR'd — CS01s are filed electronically
        # and carry one, unlike the scanned accounts.
        "shareholders": (shareholders or {}).get("shareholders", []),
        "confirmation_statement":
            (shareholders or {}).get("confirmation_statement"),
        "reads_as_no_registrable_person":
            (c.get("psc") or {}).get("reads_as_no_registrable_person", False),
        "corporate_officers": corporate_officers,
    }
    if c.get("foreign_company_details"):
        out["foreign_registry"] = c["foreign_company_details"]
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--filings", type=Path, required=True)
    ap.add_argument("--shareholders", type=Path,
                    help="Output of scripts/ch_fetch_confirmations.py. "
                         "Omit and the shareholder blocks are empty.")
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args()

    rows = json.loads(args.filings.read_text())
    rows = [r for r in rows if "error" not in r]
    holders: dict[str, dict] = {}
    if args.shareholders:
        holders = {h["company_number"]: h
                   for h in json.loads(args.shareholders.read_text())}
    doc = {
        "as_at": str(date.today()),
        "source": "Companies House public API",
        "companies": [entry(r, holders.get(r["company_number"])) for r in
                      sorted(rows, key=lambda r: r["company_name"] or "")],
    }
    text = HEADER + "\n" + yaml.safe_dump(doc, sort_keys=False,
                                          allow_unicode=True, width=76)
    args.out.write_text(text)
    n_ch = sum(1 for r in rows if r["charges"])
    n_no = sum(1 for r in rows
               if (r.get("psc") or {}).get("reads_as_no_registrable_person"))
    n_none = sum(1 for r in rows if not r["accounts_filings"])
    print(f"{len(rows)} companies written to {args.out}: {n_ch} carry "
          f"charges, {n_no} read as no registrable person, {n_none} have "
          f"filed no accounts at all.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
