#!/usr/bin/env python3
"""One markdown file per site, report and findings together, for a notebook.

Gemini Notebook (and NotebookLM) take a bounded number of sources and
read each one whole. The Drive tree gives every site two files — a prose
report and a findings CSV — which is right for a reporter opening a
folder and wrong here: 429 sites would arrive as 726 sources, over the
600 the notebook allows, and a CSV uploaded as a source reads far less
well than the same rows as a table inside the site's own report.

So this welds each pair into one document: the site report as written,
then every verified finding for that site as a markdown table beneath
it. Nothing is summarised and nothing is dropped.

**This writes to a local directory only.** It does not touch Drive, the
database, or the staging tree it reads. It is an additional export
format, not a stage in the release chain.

Source is the staging tree rather than the database, deliberately: the
report prose is generated by build_drive_staging.py, and regenerating it
here would be a second implementation of the same document, free to
drift. This reads what that script produced, so the notebook and the
Drive folder cannot disagree.

**Large sites are split, not truncated.** A notebook source is capped at
around half a million words, and the largest site here holds 130,092
findings — comfortably past it. Splitting keeps every row at the cost of
a few more files (429 sites become 506 documents at the default budget,
still under the 600 limit). Truncation was the alternative and was
rejected: a table that silently stops is worse than no table, because
nothing on the page tells the reader — or the model — that it stopped.

    scripts/export_notebook_bundle.py
    scripts/export_notebook_bundle.py --out ~/Desktop/dc_notebook
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

# Words per document, not rows. A row-based cap was tried first and set
# at 12,500 on an estimate of ~40 words a row; the real corpus averages
# ~52 and varies by site with quote length, so 49 documents came out over
# the limit. Budgeting the thing actually capped removes the estimate
# from the loop. 400,000 leaves headroom under the ~500,000-word source
# limit for the report and the headers above the table.
DEFAULT_MAX_WORDS = 400_000

# The CSV's own column order, which is the order a reporter sees in
# Excel. Kept identical so the table and the CSV are the same artefact
# in two renderings.
COLUMNS = ["application", "document file", "where in the document",
           "signal family", "signal type", "value", "number", "unit",
           "verbatim quote", "extracted by", "whose figure is this?",
           "quantity type", "adjudicated MW", "quantity note"]


def cell(text: str) -> str:
    """One CSV field as one markdown table cell.

    A pipe ends a cell and a newline ends a row, and planning quotes
    contain both — "80% - 480W | 25.4m²" is a real shape here. Escaping
    the first and folding the second is what keeps a 130,000-row table
    from collapsing into unparseable rubble halfway down.
    """
    out = (text or "").replace("\r", " ").replace("\n", " ")
    out = out.replace("|", "\\|")
    return " ".join(out.split())


def row_line(r: dict) -> str:
    return "| " + " | ".join(cell(r.get(c, "")) for c in COLUMNS) + " |"


def table_header() -> list[str]:
    return ["| " + " | ".join(COLUMNS) + " |",
            "|" + "|".join("---" for _ in COLUMNS) + "|"]


def split_by_words(rows: list[dict], budget: int) -> list[list[dict]]:
    """Group rows into parts, each under `budget` words.

    Counted from the rendered line, because that is what the notebook
    will read — a quote is most of a row's length and quote length is
    exactly what varies between sites.
    """
    if not rows:
        return [[]]
    parts, current, used = [], [], 0
    for r in rows:
        n = len(row_line(r).split())
        if current and used + n > budget:
            parts.append(current)
            current, used = [], 0
        current.append(r)
        used += n
    if current:
        parts.append(current)
    return parts


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--staging", type=Path,
                    default=Path("data/exports/drive_staging/sites"),
                    help="the per-site tree built by build_drive_staging.py")
    ap.add_argument("--out", type=Path,
                    default=Path("data/exports/notebook_bundle"),
                    help="local folder to write into; created if absent")
    ap.add_argument("--only", nargs="+", metavar="SITE_KEY",
                    help="build only these sites. For adding to a notebook "
                         "that already holds the others: a site absent from "
                         "the notebook has no source to duplicate, so its "
                         "document can be uploaded alongside them. Do NOT "
                         "use this for a site the notebook already holds — "
                         "the upload adds a second source rather than "
                         "replacing the first, and the notebook would then "
                         "hold two versions of one site with nothing to say "
                         "which is current.")
    ap.add_argument("--only-from", type=Path, metavar="FILE",
                    help="a file of site keys, one per line, same rule as "
                         "--only. Blank lines and # comments ignored.")
    ap.add_argument("--max-words", type=int, default=DEFAULT_MAX_WORDS,
                    help=f"words per document before a site's findings are "
                         f"split across parts (default {DEFAULT_MAX_WORDS:,}; "
                         f"the notebook source limit is around 500,000)")
    args = ap.parse_args()

    if not args.staging.is_dir():
        sys.exit(f"no staging tree at {args.staging} — run "
                 f"scripts/build_drive_staging.py first")

    only: set[str] | None = None
    if args.only or args.only_from:
        only = set(args.only or [])
        if args.only_from:
            only |= {ln.strip() for ln in
                     args.only_from.read_text().splitlines()
                     if ln.strip() and not ln.startswith("#")}

    args.out.mkdir(parents=True, exist_ok=True)
    if only is None:
        # Stale documents from an earlier run would be uploaded alongside
        # their replacements and read as separate sources. Same reasoning as
        # the Drive sync's prune, and safe here because this folder holds
        # nothing this script did not write.
        stale = sorted(args.out.glob("*report_and_findings*.md"))
        for f in stale:
            f.unlink()
    else:
        # Emphatically NOT pruning under --only: the prune exists to stop
        # a full rebuild leaving last run's documents behind, and applying
        # it to a partial build would delete every site the run was not
        # asked for — turning "add three sites" into "keep only three".
        print(f"--only: building {len(only)} named sites; not pruning "
              f"{args.out} (a partial build must not delete the rest)")

    n_docs = n_sites = n_rows = 0
    biggest = ("", 0)
    for site_dir in sorted(p for p in args.staging.iterdir() if p.is_dir()):
        report_path = next(site_dir.glob("_site_report — *.md"), None)
        if report_path is None:
            continue
        if only is not None and site_dir.name.split(" — ")[0] not in only:
            continue
        n_sites += 1
        stem = site_dir.name                       # "<key> — <name>"
        report = report_path.read_text(encoding="utf-8").rstrip("\n")

        csv_path = next(site_dir.glob("_findings — *.csv"), None)
        rows: list[dict] = []
        if csv_path is not None:
            with csv_path.open(encoding="utf-8-sig", newline="") as fh:
                rows = list(csv.DictReader(fh))
        n_rows += len(rows)
        if len(rows) > biggest[1]:
            biggest = (stem, len(rows))

        key, _, name = stem.partition(" — ")
        chunks = split_by_words(rows, args.max_words)
        parts = len(chunks)
        seen = 0
        for i, chunk in enumerate(chunks):
            suffix = "" if parts == 1 else f" (part {i + 1} of {parts})"
            # Every part opens with the same identification block. One
            # document is always one site — parts divide a site, they
            # never combine two — but a model retrieving a row from the
            # middle of a 400,000-word table has only what is on the
            # page, so the page has to say whose row it is. The filename
            # says so too; this is the belt to that pair of braces.
            body = [f"# {name}", "",
                    f"**Site:** {name}  ",
                    f"**Site key:** `{key}`  ",
                    "**Document:** site report and verified findings"
                    + (f", part {i + 1} of {parts}" if parts > 1 else "")
                    + "  ",
                    "**Every row below belongs to this site and no other.**",
                    ""]
            if i == 0:
                body += ["---", "", report, ""]
            else:
                body += [
                    "---", "",
                    f"This continues the findings for **{name}** "
                    f"(`{key}`). The site report and the first {seen:,} of "
                    f"its {len(rows):,} findings are in part "
                    f"{'1' if i == 1 else f'1 to {i}'} of this document.", ""]
            body += ["## Verified findings", ""]
            if not rows:
                body += [
                    "No verified findings were extracted from this site's "
                    "documents. That is not the same as nothing being there: "
                    "see the reading coverage stated above.", ""]
            else:
                body += [
                    f"{len(rows):,} verified findings for {name}"
                    + (f", of which rows {seen + 1:,}–{seen + len(chunk):,} "
                       f"appear below" if parts > 1 else "")
                    + ". Every row names the document it came from, where in "
                    "that document it appears — only a PDF has pages, so "
                    "a Word file cites a section and a workbook a sheet — "
                      "the verbatim quote and the model that read it. Every "
                      "quote was checked against the source text before it was "
                      "stored.", "",
                    "**Read the 'whose figure is this?' column before quoting "
                    "any megawatt number.** Planning documents argue for "
                    "approval by citing the market, so a figure appearing in "
                    "this site's documents is often about something else "
                    "entirely — a national policy target, a competitor's "
                    "scheme, a sector forecast. Only rows marked *this "
                    "development* describe the site. A blank means the finding "
                    "is not a power figure and was never put to adjudication, "
                    "which is different from having been judged and set "
                    "aside.", ""]
                body += table_header()
                body += [row_line(r) for r in chunk]
                body.append("")
            body += [f"*End of {name} (`{key}`)"
                     + (f", part {i + 1} of {parts}" if parts > 1 else "")
                     + ".*", ""]
            seen += len(chunk)
            out_path = args.out / f"{stem} — report_and_findings{suffix}.md"
            out_path.write_text("\n".join(body) + "\n", encoding="utf-8")
            n_docs += 1

    total_mb = sum(f.stat().st_size for f in args.out.glob("*.md")) / 1e6
    if stale:
        print(f"removed {len(stale)} document(s) from a previous run")
    print(f"{n_sites} sites, {n_rows:,} findings rows -> {n_docs} documents "
          f"({total_mb:.1f} MB) in {args.out}")
    print(f"  largest site: {biggest[0][:60]} ({biggest[1]:,} findings)")
    if n_docs >= 600:
        print(f"  WARNING: {n_docs} documents is at or over the 600-source "
              f"notebook limit — raise --max-rows to merge parts back up.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
